name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06ac96dfaf5d6d575f22c34852275c4b84cde5e629fa53fb83a462a8b4a98880"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
