name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d207da1625ba9a8c346d653899ffece17de6b74c7f46ec932892d1a4b8f30789"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
