name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7030a9c449d40f094eb5d01ae6f3dd77efea08ec4810846b08c9e02245c9a9f"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
