name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26411110d848ac2febe53a1b92ee96bddcff1434c25a3a476c4710a1c20877ff"

[versions]
fabric = "0.16.7"
minecraft = "1.21"
