name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3af2b77bfbbf80e3cb9fe7283da18a9592fab9a44a3006f79c8244a0cb7a0a9"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
