name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ea1ff2b1cd7df6f16b79d7abbe77f26ab11814ff2261df4eae1a23185f09324"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
