name = "MC1.21"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf9aded4d318a2d362d683576fb6a31962dd040b41422e826fa126407ed78fa2"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
