name = "MC1.21.4"
author = "TN_TechNoob"
version = "v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74f4fce19c05bc4a0b9a063f2aaf98a5f26acbe6d730f086c84e4e62dec7058a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
