name = "MC1.19.2"
author = "TN_TechNoob"
version = "v2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b081067a6ca86f03c2236e494dee06d9e94ae97faa131a1f5c356b05265cf9a"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
