name = "MC1.19.2"
author = "TN_TechNoob"
version = "v1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b64d26fd4cd05c42166e8d252339a43f0d109278462bdabec25893797a5287"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"
