name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5c5d764a993c06aa7089c63e5e38d5c803eba307c45e5f49c117a9bb9451516"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
