name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62ab53deed80e604cee73a7015ccfb4f9513a4f0c9c7b5d0292fc86445ade388"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
