name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d2edf0632d5751cfc59080a9f0ca36ee002910bbfac39a0089664e29e4419f8"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
