name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.0.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad066be4d41763ebf318910cf64fde06e9ebc47a04c294257c92123963711755"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
