name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6878ba29d4ae17ec1424cab469a39a64f37dc0e01dae2f52b71d1b293a2ac1cc"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
