name = "MC1.21.4"
author = "TN_TechNoob"
version = "v1.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdb7048b64e7225f100a999fc5a80e21f654ea0b979e57c2729c4cdbb7be5a21"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
