name = "MC1.21.4"
author = "TN_TechNoob"
version = "v1.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7cefaf6eb3d82ffb050f2f3390809e2101467f580c8c0bb83430272360e243d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
