name = "MC1.21.4"
author = "TN_TechNoob"
version = "v2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ea8d0613617dcf577f026c089648373752f31d082b9d275eab59b7fee6e3e19"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
