name = "MC1.21.1"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcfa7fe35fc42541cc7667352d5f2213a480f78a5832ae4cfa9572aca5d99e73"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
