name = "MC1.20.1"
author = "TN_TechNoob"
version = "v4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d7fbd12ede5255d444549f86385bf70dddb90bdb80cd0f31c0682f6394b3e5"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
