name = "MC1.20.1"
author = "TN_TechNoob"
version = "v4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e5f8cf92139d64fd8c0b5204d370b5472e42b494d25adfaffbb155e58017afe"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
