name = "MC1.20.1"
author = "TN_TechNoob"
version = "v6.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3c2cbb7a1c5e9a3369c05fe06513d34f6f0e1a42f5527329c1e8d85958e375e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
