name = "MC1.20.1"
author = "TN_TechNoob"
version = "v6.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d60fb8ed254a6abc4918261676e9984cf38b5528ab0b34be0de2b1b74a264b9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
