name = "MC1.20.6"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "112873d12a57378d4f60fa243a7ae89d6efaf496c3bff7aaa8bc89d316bddf3e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
