name = "MC1.20.6"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bd746b1ba4b9445d59ca5c724fff47ed4e87027a4020e6d4f58a075919b0423"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
