name = "MC1.18.2"
author = "TN_TechNoob"
version = "v3.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ace8a2895294ae7049f96285332d69de867b89462beb3ecb0ec7431f4f49f32"

[versions]
fabric = "0.16.9"
minecraft = "1.18.2"
