name = "MC1.18.2"
author = "TN_TechNoob"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "424860bd4ddbcea2a66bb78dc01e42a06a646415f0024c2f1446b57ebfbbc235"

[versions]
fabric = "0.15.11"
minecraft = "1.18.2"
