name = "MC1.18.2"
author = "TN_TechNoob"
version = "v3.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "585f9caea5319e7a580e8aadad65bff937f3aead21716c00d170d3bc18f38690"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
