name = "MC1.18.2"
author = "TN_TechNoob"
version = "v4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48b9970a2352651c45bcb4d2ce70b61ec7530131ff803bb0d2ca7b89aee49373"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
