name = "MC1.18.2"
author = "TN_TechNoob"
version = "v4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09482ba2a4e040a85e70fc0fbbcc14ffd0655815bc5021fa92b9ef27270fe493"

[versions]
fabric = "0.16.14"
minecraft = "1.18.2"
