name = "MC1.18.2"
author = "TN_TechNoob"
version = "v3.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a652e8459b6ad168f459678f5b4bd36d881c20682a6079a6ddd4cb2919a977"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
